(()=>{const TILE=48,map=AdventureV1Map.createMap();let state=GameState.load(),planned=null,moving=false,visible=new Set();const $=id=>document.getElementById(id),mapEl=$('adventureMap'),view=$('mapViewport'),status=$('mapStatus'),modal=$('modal');
function key(x,y){return `${x},${y}`} function objVisible(o){return visible.has(key(o.x,o.y))||(state.map.discoveredTiles||[]).includes(key(o.x,o.y));}
function activeObjects(){return map.objects.filter(o=>!state.map.collectedObjectIds.includes(o.id)&&!state.map.defeatedArmyIds.includes(o.id));}
function blockers(ignoreId){return activeObjects().filter(o=>o.blocksMovement&&o.id!==ignoreId).map(o=>({x:o.x,y:o.y}));}
function refreshVisibility(){visible=new Set(AdventureCore.visibleTiles(state.hero.x,state.hero.y,map.width,map.height,5).map(p=>key(p.x,p.y)));const d=new Set(state.map.discoveredTiles||[]);for(const k of visible)d.add(k);state.map.discoveredTiles=[...d];}
function resourceLabel(k){return({stone:'Kamień',wood:'Drewno',mercury:'Rtęć',sulfur:'Siarka',gems:'Klejnoty',gold:'Złoto',soulMushrooms:'Grzyby Dusz'})[k]||k}
function renderHUD(){for(const k of GameState.RESOURCE_KEYS){const e=$(`res-${k}`);if(e)e.textContent=state.resources[k]||0}$('calendarLabel').textContent=`Miesiąc ${state.calendar.month} • Tydzień ${state.calendar.week} • Dzień ${state.calendar.day}`;$('heroName').textContent=state.hero.name;$('heroStats').innerHTML=`Poziom <b>${state.hero.level}</b> • XP <b>${state.hero.xp}</b><br>Atak ${state.hero.attack} • Obrona ${state.hero.defense}<br>Moc ${state.hero.power} • Wiedza ${state.hero.knowledge}`;$('moveBar').max=state.hero.maxMovement;$('moveBar').value=state.hero.movement;$('moveText').textContent=`${state.hero.movement} / ${state.hero.maxMovement}`;$('armyBar').innerHTML=Array.from({length:7},(_,i)=>{const u=state.hero.army[i];return `<div class="army-slot ${u?'':'empty'}">${u?`<b>${u.name}</b><small>${u.count} szt.</small>`:'<b>—</b>'}</div>`}).join('')}
function renderMap(){refreshVisibility();mapEl.querySelectorAll('*').forEach(n=>n.remove());for(const t of map.tiles){const d=document.createElement('div'),k=key(t.x,t.y);d.className=`tile terrain-${t.terrain}${t.road?' road-'+t.road:''}${visible.has(k)?'':state.map.discoveredTiles.includes(k)?' fog-explored':' fog-hidden'}`;d.style.left=t.x*TILE+'px';d.style.top=t.y*TILE+'px';d.dataset.x=t.x;d.dataset.y=t.y;d.onclick=()=>planTo(t.x,t.y,null);mapEl.appendChild(d)}
if(planned){planned.path.forEach((p,i)=>{const e=mapEl.querySelector(`[data-x="${p.x}"][data-y="${p.y}"]`);if(e)e.classList.add(i<planned.todayCount?'route-today':'route-later')});const e=mapEl.querySelector(`[data-x="${planned.goal.x}"][data-y="${planned.goal.y}"]`);if(e)e.classList.add('target')}
for(const o of activeObjects()){if(!objVisible(o))continue;const e=document.createElement('div');e.className='object';e.style.left=o.x*TILE+'px';e.style.top=o.y*TILE+'px';e.innerHTML=`${o.icon||'◆'}<span class="label">${o.name}</span>`;e.onclick=ev=>{ev.stopPropagation();planTo(o.x,o.y,o)};mapEl.appendChild(e)}const h=document.createElement('div');h.className='hero';h.style.left=state.hero.x*TILE+'px';h.style.top=state.hero.y*TILE+'px';h.textContent='🧙‍♂️';mapEl.appendChild(h);drawMinimap();renderHUD();GameState.save(state)}
function planTo(x,y,obj){if(moving)return;let goal={x,y};if(obj?.blocksMovement){const candidates=AdventureCore.neighbors(x,y,map.width,map.height).filter(p=>!blockers(obj.id).some(b=>b.x===p.x&&b.y===p.y));let best=null;for(const p of candidates){const path=AdventureCore.findPath(map,{x:state.hero.x,y:state.hero.y},p,blockers(obj.id));if(path&&(!best||path.length<best.path.length))best={goal:p,path}}if(!best){status.textContent='Brak dojścia do celu.';return}goal=best.goal}
const path=AdventureCore.findPath(map,{x:state.hero.x,y:state.hero.y},goal,blockers(obj?.id));if(!path){status.textContent='Nie można wyznaczyć trasy.';return}const split=AdventureCore.splitPathByMovement(path,map,state.hero.movement,{x:state.hero.x,y:state.hero.y});const same=planned&&planned.goal.x===goal.x&&planned.goal.y===goal.y&&planned.objectId===(obj?.id||null);planned={goal,path,todayCount:split.today.length,objectId:obj?.id||null};renderMap();status.textContent=same?'Bohater rusza…':'Kliknij ten sam cel ponownie, aby ruszyć.';if(same)movePlanned(obj)}
async function movePlanned(obj){if(moving||!planned)return;moving=true;for(const p of [...planned.path]){const cost=AdventureCore.stepCost({x:state.hero.x,y:state.hero.y},p,AdventureCore.tileAt(map,p.x,p.y));if(cost>state.hero.movement)break;state.hero.movement-=cost;state.hero.x=p.x;state.hero.y=p.y;planned.path.shift();refreshVisibility();renderMap();await new Promise(r=>setTimeout(r,90))}moving=false;const reached=state.hero.x===planned.goal.x&&state.hero.y===planned.goal.y;if(reached&&obj)interact(obj);planned=null;renderMap()}
function interact(o){if(o.type==='resource'){state.resources[o.resource]+=o.amount;state.map.collectedObjectIds.push(o.id);status.textContent=`Zebrano: ${o.amount} ${resourceLabel(o.resource)}.`}else if(o.type==='resourceStructure'){if(o.guardedBy&&!state.map.defeatedArmyIds.includes(o.guardedBy)){status.textContent='Struktura jest chroniona.';return}if(!state.map.ownedStructureIds.includes(o.id))state.map.ownedStructureIds.push(o.id);status.textContent=`Przejęto: ${o.name}. +${o.produces.amount} ${resourceLabel(o.produces.resource)} dziennie.`}else if(o.type==='town'){if(!state.map.capturedTownIds.includes(o.id))state.map.capturedTownIds.push(o.id);GameState.save(state);location.href=`town.html?town=${encodeURIComponent(o.id)}`;return}else if(o.type==='chest'){showModal(o.name,'Wybierz nagrodę',[['1000 złota',()=>{state.resources.gold+=1000;collect(o)}],['750 XP',()=>{state.hero.xp+=750;levelHero();collect(o)}]])}else if(o.type==='neutralArmy'){BattleBridge.startBattle(state,{battleId:o.id,enemyArmy:o.army,xpReward:o.xpReward,enemyObjectId:o.id,guards:o.guards});GameState.save(state);location.href='index.html?campaign=1';return}GameState.save(state);renderMap();checkVictory()}
function collect(o){if(!state.map.collectedObjectIds.includes(o.id))state.map.collectedObjectIds.push(o.id);hideModal();GameState.save(state);renderMap()}
function levelHero(){const thresholds=[0,1000,2500,4500];while(state.hero.level<4&&state.hero.xp>=thresholds[state.hero.level]){state.hero.level++; if(state.hero.level%2)state.hero.defense++;else state.hero.attack++;}}
function showModal(title,text,actions){$('modalTitle').textContent=title;$('modalText').textContent=text;$('modalActions').innerHTML='';for(const[a,fn]of actions){const b=document.createElement('button');b.textContent=a;b.onclick=fn;$('modalActions').appendChild(b)}modal.classList.remove('hidden')}function hideModal(){modal.classList.add('hidden')}
function endDay(){GameState.endDay(state,map.objects,TownCore);if(state.hero.temporaryBonuses)state.hero.temporaryBonuses={};planned=null;status.textContent='Rozpoczął się nowy dzień.';GameState.save(state);renderMap()}
function drawMinimap(){const c=$('minimap'),ctx=c.getContext('2d'),sx=c.width/map.width,sy=c.height/map.height;ctx.clearRect(0,0,c.width,c.height);const colors={grass:'#476b37',dirt:'#765a38',rock:'#66645d',sand:'#a28d55',snow:'#aab8b7',swamp:'#374d3a'};for(const t of map.tiles){const k=key(t.x,t.y);ctx.fillStyle=!state.map.discoveredTiles.includes(k)?'#050605':visible.has(k)?colors[t.terrain]:'#252a23';ctx.fillRect(t.x*sx,t.y*sy,Math.ceil(sx),Math.ceil(sy))}ctx.fillStyle='#fff27a';ctx.fillRect(state.hero.x*sx,state.hero.y*sy,Math.max(3,sx),Math.max(3,sy))}
function centerHero(){view.scrollLeft=Math.max(0,state.hero.x*TILE-view.clientWidth/2);view.scrollTop=Math.max(0,state.hero.y*TILE-view.clientHeight/2)}function checkVictory(){if(state.map.ownedStructureIds.includes('gold-mine-main')){$('objective').textContent='Zwycięstwo: Opuszczona Kopalnia Złota należy do Ciebie!';state.scenarioStatus='won'}}
$('endDayBtn').onclick=endDay;$('centerHeroBtn').onclick=centerHero;$('newGameBtn').onclick=()=>{if(confirm('Rozpocząć nową grę?')){state=GameState.reset();location.reload()}};window.addEventListener('keydown',e=>{const d=48;if(e.key==='ArrowLeft'||e.key==='a')view.scrollLeft-=d;if(e.key==='ArrowRight'||e.key==='d')view.scrollLeft+=d;if(e.key==='ArrowUp'||e.key==='w')view.scrollTop-=d;if(e.key==='ArrowDown'||e.key==='s')view.scrollTop+=d});
if(state.lastBattleResult&&window.BattleBridge)BattleBridge.consumeAdventureResult(state);refreshVisibility();renderMap();centerHero();checkVictory();})();
