(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./town-core.js'):root.TownCore,typeof module==='object'&&module.exports?require('./game-state.js'):root.GameState);if(typeof module==='object'&&module.exports)module.exports=api;else{root.BattleBridge=api;api.installBrowserBridge?.(root);}})(typeof globalThis!=='undefined'?globalThis:this,function(TownCore,GameState){
function clone(v){return JSON.parse(JSON.stringify(v));}
function startBattle(state,spec){state.pendingBattle={battleId:spec.battleId,enemyArmy:clone(spec.enemyArmy||[]),xpReward:spec.xpReward||0,enemyObjectId:spec.enemyObjectId||spec.battleId,guards:spec.guards||null,started:true};state.lastBattleResult=null;return state.pendingBattle;}
function getBattleSetup(state){if(!state?.pendingBattle)return null;return{battleId:state.pendingBattle.battleId,playerArmy:clone(state.hero.army||[]),enemyArmy:clone(state.pendingBattle.enemyArmy||[]),hero:clone(state.hero),xpReward:state.pendingBattle.xpReward||0};}
function recordResult(state,result){if(!state.pendingBattle)return null;state.lastBattleResult={...clone(result),battleId:state.pendingBattle.battleId,enemyObjectId:state.pendingBattle.enemyObjectId,xpReward:state.pendingBattle.xpReward||0,consumed:false};return state.lastBattleResult;}
function consumeAdventureResult(state){const r=state?.lastBattleResult;if(!r||r.consumed)return r;if(r.outcome==='victory'){state.hero.army=clone(r.survivingArmy||[]);state.hero.xp=(state.hero.xp||0)+(r.xpReward||0);if(r.enemyObjectId&&!state.map.defeatedArmyIds.includes(r.enemyObjectId))state.map.defeatedArmyIds.push(r.enemyObjectId);if(state.hero.faction==='necropolis'&&TownCore){const necroTown=Object.values(state.towns||{}).find(t=>t.faction==='necropolis');TownCore.applyNecromancy({defeatedModels:r.defeatedModels||0,altar:!!necroTown?.buildings?.includes('necroSoulAltar')},state.resources,state.hero.army);}}else state.scenarioStatus='lost';r.consumed=true;state.pendingBattle=null;return r;}
function toBattleStack(s,team,i){const left=team==='player';return{...clone(s),id:`${team}-${s.unitId||i}-${i}`,team,type:s.type||'skeleton',variant:s.variant||'',c:left?2:12,r:2+i*2,count:s.count||0,totalHp:s.totalHp??((s.count||0)*(s.hpPer||10)),size:s.size||1,facing:s.facing||(left?'right':'left'),dead:false,retaliatedRound:0,anim:'idle',effects:[],baseSpeed:s.speed,defending:false,waitedRound:0,shots:s.shots??s.maxShots??0,maxShots:s.maxShots??s.shots??0};}
function installBrowserBridge(root){if(typeof document==='undefined'||!root.CombatCore||!root.GameState)return;const battlefield=document.getElementById('battlefield');if(!battlefield)return;let state=GameState.load(),setup=getBattleSetup(state),injected=false,finished=false;if(!setup)return;const originalOrder=root.CombatCore.buildInitiativeOrder;root.CombatCore.buildInitiativeOrder=function(units){if(!injected&&setup){const p=setup.playerArmy.map((s,i)=>toBattleStack(s,'player',i)),a=setup.enemyArmy.map((s,i)=>toBattleStack(s,'ai',i));units.splice(0,units.length,...p,...a);injected=true;}return originalOrder(units);};setTimeout(()=>{try{if(typeof v4!=='undefined'&&setup?.hero){Object.assign(v4.heroes.player,{name:setup.hero.name||'Aldren',attack:setup.hero.attack||0,defense:setup.hero.defense||0,power:setup.hero.power||0});}if(typeof checkEnd==='function'){const originalCheck=checkEnd;checkEnd=function(){const ended=originalCheck();if(ended&&!finished&&setup){finished=true;const playerAlive=game.units.filter(u=>u.team==='player'&&CombatCore.isAlive(u));const enemyInitial=(state.pendingBattle?.enemyArmy||[]).reduce((n,u)=>n+(u.count||0),0);recordResult(state,{outcome:playerAlive.length?'victory':'defeat',survivingArmy:playerAlive.map(u=>({unitId:u.unitId||u.id.split('-').slice(1,-1).join('-'),name:u.name,type:u.type,variant:u.variant||'',count:u.count,hpPer:u.hpPer,totalHp:u.totalHp,minDmg:u.minDmg,maxDmg:u.maxDmg,speed:u.baseSpeed||u.speed,attack:u.attack,defense:u.defense,size:u.size||1,mounted:!!u.mounted,ranged:!!u.ranged,shots:u.shots,maxShots:u.maxShots})),defeatedModels:enemyInitial});GameState.save(state);const st=document.getElementById('statusText');if(st)st.textContent+=(playerAlive.length?' Powrót na mapę przygody…':' Scenariusz przegrany.');setTimeout(()=>location.href='adventure.html',1000);}return ended;};}const restart=document.getElementById('restartBtn');if(restart){restart.textContent='← Wróć na mapę';restart.onclick=()=>{location.href='adventure.html';};}}catch(e){console.error('Campaign bridge:',e)}},0);}
return{startBattle,getBattleSetup,recordResult,consumeAdventureResult,toBattleStack,installBrowserBridge};
});
