const v4={selectedSpell:null,log:[],heroes:{player:{name:'Aldren',icon:'🧙‍♂️',attack:2,defense:1,power:3,mana:30,maxMana:30,castRound:0},ai:{name:'Morvanna',icon:'🧙‍♀️',attack:1,defense:2,power:2,mana:25,maxMana:25,castRound:0}}};
const V4_SPELLS={arrow:{id:'arrow',name:'Magiczna Strzała',icon:'✨',cost:8,target:'enemy',desc:'25 + 10×Moc obrażeń'},bless:{id:'bless',name:'Błogosławieństwo',icon:'☀️',cost:6,target:'ally',desc:'Maksymalne obrażenia przez 2 rundy'},haste:{id:'haste',name:'Przyspieszenie',icon:'⚡',cost:7,target:'ally',desc:'+2 Szybkości przez 2 rundy'},slow:{id:'slow',name:'Spowolnienie',icon:'❄️',cost:7,target:'enemy',desc:'−2 Szybkości przez 2 rundy'}};
const waitBtn=document.getElementById('waitBtn'),defendBtn=document.getElementById('defendBtn'),spellBtn=document.getElementById('spellBtn'),spellbook=document.getElementById('spellbook'),spellGrid=document.getElementById('spellGrid'),spellHelp=document.getElementById('spellHelp'),battleLog=document.getElementById('battleLog'),playerHeroCard=document.getElementById('playerHeroCard'),aiHeroCard=document.getElementById('aiHeroCard'),roundLabel=document.getElementById('roundLabel'),actionHint=document.getElementById('actionHint');
function v4Log(text,type=''){v4.log.unshift({text,type});v4.log=v4.log.slice(0,30);v4RenderLog();}
function v4InitUnits(){game.units.forEach(u=>{u.effects=u.effects||[];u.baseSpeed=u.baseSpeed??u.speed;u.defending=false;u.waitedRound=u.waitedRound||0;});}
function v4Hero(team){return v4.heroes[team];}
function v4RecalcSpeed(u){const haste=CombatCore.effect(u,'haste'),slow=CombatCore.effect(u,'slow');u.speed=Math.max(1,u.baseSpeed+(haste?.amount||slow?.amount||0));}
function v4TickEffects(){game.units.forEach(u=>{CombatCore.tickEffects(u);v4RecalcSpeed(u);});}
function v4EffectiveAttack(u){return u.attack+(v4Hero(u.team)?.attack||0);}
function v4EffectiveDefense(u){return CombatCore.effectiveDefense(u)+(v4Hero(u.team)?.defense||0);}
const v3Reset=reset;
reset=function(){v4.selectedSpell=null;v4.log=[];v4.heroes.player={name:'Aldren',icon:'🧙‍♂️',attack:2,defense:1,power:3,mana:30,maxMana:30,castRound:0};v4.heroes.ai={name:'Morvanna',icon:'🧙‍♀️',attack:1,defense:2,power:2,mana:25,maxMana:25,castRound:0};v3Reset();v4InitUnits();v4Log('Rozpoczyna się bitwa.');render();};
const v3StartRound=startRound;
startRound=function(){if(game?.round>1)v4TickEffects();v3StartRound();};
const v3BeginTurn=beginTurn;
beginTurn=async function(){const next=game?.order?.[game.turnIndex];if(next)CombatCore.clearTurnStance(next);v4.selectedSpell=null;await v3BeginTurn();};
const v3RollDamage=rollDamage;
rollDamage=function(a,d,mode){const aa=a.attack,dd=d.defense;a.attack=v4EffectiveAttack(a);d.defense=v4EffectiveDefense(d);let dmg;if(CombatCore.effect(a,'bless')){const range=mode==='ranged'?rangedPenalty(a,d):1;dmg=Math.max(1,Math.round(a.maxDmg*a.count*CombatCore.damageMultiplier(a.attack,d.defense)*range));}else dmg=v3RollDamage(a,d,mode);a.attack=aa;d.defense=dd;return dmg;};
const v3Strike=strike;
strike=async function(a,d,mode,isRetaliation=false){const before=d.totalHp,result=await v3Strike(a,d,mode,isRetaliation);v4Log(`${a.name}${isRetaliation?' kontratakuje i':''} zadaje ${Math.max(0,before-d.totalHp)} obrażeń ${d.name}.`,a.team==='ai'?'ai':'');if(d.dead)v4Log(`${d.name} zostaje pokonany.`);return result;};
const v3AddHitbox=addHitbox;
addHitbox=function(u){v3AddHitbox(u);const hb=BF.querySelector(`.unit-hitbox[data-id="${u.id}"]`);if(hb&&v4.selectedSpell){hb.style.cursor='pointer';hb.onclick=()=>v4CastSelected(u);}};
const v3Render=render;
render=function(rebuild=true){v3Render(rebuild);v4Render();};
function v4Wait(){if(game.busy||game.over)return;const u=active();if(!u||u.team!=='player'||u.waitedRound===game.round)return;u.waitedRound=game.round;game.order.splice(game.turnIndex,1);game.order.push(u);v4Log(`${u.name} czeka i zagra później w tej rundzie.`);statusText.textContent=`${u.name} czeka.`;render();beginTurn();}
function v4Defend(){if(game.busy||game.over)return;const u=active();if(!u||u.team!=='player')return;CombatCore.applyDefend(u);v4Log(`${u.name} przyjmuje postawę obronną (+2 Obrony).`);endTurn();}
function v4ToggleSpellbook(force){const open=force??spellbook.classList.contains('hidden');spellbook.classList.toggle('hidden',!open);v4RenderSpells();}
function v4SelectSpell(id){const h=v4.heroes.player,s=V4_SPELLS[id];if(h.castRound===game.round){spellHelp.textContent='Bohater rzucił już czar w tej rundzie.';return;}if(h.mana<s.cost){spellHelp.textContent='Za mało many.';return;}v4.selectedSpell=id;spellHelp.textContent=`${s.name}: kliknij ${s.target==='ally'?'sojuszniczą':'wrogą'} jednostkę.`;v4RenderSpells();render();}
function v4MagicDamage(target,dmg){applyDamage(target,dmg);showDamage(target,dmg,'Magia');if(target.totalHp<=0){target.dead=true;target.anim='death';}render();}
function v4SpellFx(target,icon){const p=pos(target.c,target.r),el=document.createElement('div');el.className='spell-fx';el.style.left=p.x+'px';el.style.top=(p.y-25)+'px';el.textContent=icon;BF.appendChild(el);setTimeout(()=>el.remove(),800);}
function v4CastSelected(target){if(!v4.selectedSpell||game.busy||game.over)return;const s=V4_SPELLS[v4.selectedSpell],h=v4.heroes.player;if((s.target==='ally'&&target.team!=='player')||(s.target==='enemy'&&target.team!=='ai')){spellHelp.textContent='Nieprawidłowy cel.';return;}if(!CombatCore.spendMana(h,s.cost))return;h.castRound=game.round;if(s.id==='arrow'){const dmg=CombatCore.magicArrowDamage(h);v4MagicDamage(target,dmg);v4Log(`${h.name} rzuca Magiczną Strzałę na ${target.name}: ${dmg} obrażeń.`,'magic');v4SpellFx(target,'✨');}else if(s.id==='bless'){CombatCore.upsertEffect(target,{id:'bless',name:'Błogosławieństwo',rounds:2});v4Log(`${h.name} błogosławi ${target.name} na 2 rundy.`,'magic');v4SpellFx(target,'☀️');}else if(s.id==='haste'){target.effects=target.effects.filter(e=>e.id!=='slow');CombatCore.upsertEffect(target,{id:'haste',name:'Przyspieszenie',amount:2,rounds:2});v4RecalcSpeed(target);v4Log(`${h.name} przyspiesza ${target.name}.`,'magic');v4SpellFx(target,'⚡');}else if(s.id==='slow'){target.effects=target.effects.filter(e=>e.id!=='haste');CombatCore.upsertEffect(target,{id:'slow',name:'Spowolnienie',amount:-2,rounds:2});v4RecalcSpeed(target);v4Log(`${h.name} spowalnia ${target.name}.`,'magic');v4SpellFx(target,'❄️');}v4.selectedSpell=null;v4ToggleSpellbook(false);render();checkEnd();}
const v3AiTurn=aiTurn;
aiTurn=async function(u){const h=v4.heroes.ai;if(h.castRound!==game.round&&h.mana>=8){const targets=alive('player').sort((a,b)=>a.totalHp-b.totalHp);const t=targets[0];if(t&&(t.totalHp<=CombatCore.magicArrowDamage(h)||Math.random()<.35)){const dmg=CombatCore.magicArrowDamage(h);CombatCore.spendMana(h,8);h.castRound=game.round;v4MagicDamage(t,dmg);v4SpellFx(t,'✨');v4Log(`${h.name} rzuca Magiczną Strzałę na ${t.name}: ${dmg} obrażeń.`,'magic');if(checkEnd())return;}}return v3AiTurn(u);};
function v4RenderHeroes(){for(const [team,el] of [['player',playerHeroCard],['ai',aiHeroCard]]){const h=v4.heroes[team],cast=h.castRound===game.round?'czar wykorzystany':'czar gotowy';el.innerHTML=`<div class="hero-portrait">${h.icon}</div><div><div class="hero-name">${h.name}</div><div class="hero-meta">Atak +${h.attack} · Obrona +${h.defense} · Moc ${h.power}<br>${cast}</div></div><div class="mana">💧 ${h.mana}/${h.maxMana}</div>`;}}
function v4RenderActions(){const pt=active()?.team==='player'&&!game.busy&&!game.over;waitBtn.disabled=!pt||active()?.waitedRound===game.round;defendBtn.disabled=!pt;spellBtn.disabled=game.over||v4.heroes.player.castRound===game.round;actionHint.textContent=v4.heroes.player.castRound===game.round?'Czar bohatera wykorzystany w tej rundzie.':`Mana: ${v4.heroes.player.mana}/${v4.heroes.player.maxMana} · 1 czar na rundę.`;}
function v4RenderSpells(){if(!spellGrid)return;const h=v4.heroes.player;spellGrid.innerHTML=Object.values(V4_SPELLS).map(s=>`<button class="spell ${v4.selectedSpell===s.id?'selected':''}" data-spell="${s.id}" ${h.mana<s.cost||h.castRound===game.round?'disabled':''}><span class="spell-icon">${s.icon}</span><span><b>${s.name}</b><br><small>${s.desc}</small></span><span class="spell-cost">${s.cost}💧</span></button>`).join('');spellGrid.querySelectorAll('[data-spell]').forEach(b=>b.onclick=()=>v4SelectSpell(b.dataset.spell));}
function v4RenderLog(){if(!battleLog)return;battleLog.innerHTML=v4.log.map((x,i)=>`<div class="log-entry ${x.type}"><strong>${v4.log.length-i}.</strong> ${x.text}</div>`).join('');}
function v4EnhanceUnitCard(){const shown=game.units.find(u=>u.id===inspectedUnitId)||active();if(!shown||!unitCard)return;const effects=(shown.effects||[]).map(e=>`<span class="effect-chip ${e.id==='slow'?'bad':''}">${e.name||e.id} · ${e.rounds}</span>`).join('');const extra=`<div class="effects">${effects||'<span class="effect-chip">Brak efektów</span>'}${shown.defending?'<span class="effect-chip">Obrona +2</span>':''}</div>`;if(!unitCard.querySelector('.effects'))unitCard.insertAdjacentHTML('beforeend',extra);}
function v4Render(){if(!game)return;v4RenderHeroes();v4RenderActions();v4RenderSpells();v4RenderLog();v4EnhanceUnitCard();if(roundLabel)roundLabel.textContent=game.round;if(initiativeQueue)initiativeQueue.querySelectorAll('.queue-unit').forEach((el,i)=>{if(game.order[i]?.waitedRound===game.round)el.classList.add('waiting');});}
waitBtn.onclick=v4Wait;defendBtn.onclick=v4Defend;spellBtn.onclick=()=>v4ToggleSpellbook();document.getElementById('closeSpellBtn').onclick=()=>{v4.selectedSpell=null;v4ToggleSpellbook(false);render();};
v4InitUnits();v4Log('Combat v4 aktywny: bohaterowie i magia gotowi.');render();
