(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.TownCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
const UNITS={
 militia:{id:'militia',name:'Milicjant',faction:'castle',tier:1,cost:{gold:55},growth:14,hpPer:10,minDmg:1,maxDmg:3,speed:5,attack:4,defense:4,type:'skeleton',size:1},
 crossbowman:{id:'crossbowman',name:'Kusznik',faction:'castle',tier:2,cost:{gold:110},growth:9,hpPer:12,minDmg:2,maxDmg:4,speed:5,attack:6,defense:4,type:'skeleton',ranged:true,shots:10,size:1},
 squire:{id:'squire',name:'Giermek',faction:'castle',tier:3,cost:{gold:180},growth:7,hpPer:20,minDmg:3,maxDmg:5,speed:5,attack:7,defense:8,type:'skeleton',size:1},
 griffinGuard:{id:'griffinGuard',name:'Gryfi Strażnik',faction:'castle',tier:4,cost:{gold:320},growth:4,hpPer:35,minDmg:5,maxDmg:8,speed:7,attack:9,defense:9,type:'skeleton',size:2},
 lightPriest:{id:'lightPriest',name:'Kapłan Światła',faction:'castle',tier:5,size:1}, knight:{id:'knight',name:'Rycerz',faction:'castle',tier:6,size:2,mounted:true}, paladin:{id:'paladin',name:'Paladyn',faction:'castle',tier:7,size:2,mounted:true},
 skeleton:{id:'skeleton',name:'Szkielet',faction:'necropolis',tier:1,cost:{gold:45},growth:16,hpPer:10,minDmg:2,maxDmg:4,speed:5,attack:5,defense:4,type:'skeleton',size:1},
 boneArcher:{id:'boneArcher',name:'Kościany Łucznik',faction:'necropolis',tier:2,cost:{gold:100},growth:9,hpPer:8,minDmg:2,maxDmg:3,speed:6,attack:6,defense:3,type:'skeleton',variant:'archer',ranged:true,shots:8,size:1},
 tombGuard:{id:'tombGuard',name:'Strażnik Grobowca',faction:'necropolis',tier:3,cost:{gold:200},growth:6,hpPer:24,minDmg:4,maxDmg:6,speed:4,attack:7,defense:9,type:'skeleton',variant:'guard',size:1},
 phantomRider:{id:'phantomRider',name:'Widmowy Jeździec',faction:'necropolis',tier:4,cost:{gold:350,soulMushrooms:1},growth:4,hpPer:38,minDmg:6,maxDmg:9,speed:8,attack:10,defense:8,type:'skeleton',size:2,mounted:true},
 lich:{id:'lich',name:'Lisz',faction:'necropolis',tier:5,size:1,ranged:true}, vampireLord:{id:'vampireLord',name:'Wampirzy Lord',faction:'necropolis',tier:6,size:1}, necromancerArchmage:{id:'necromancerArchmage',name:'Arcymag Nekromancji',faction:'necropolis',tier:7,size:1,ranged:true,magic:true}
};
const BUILDINGS={
 castleBarracks:{id:'castleBarracks',faction:'castle',name:'Koszary Milicji',cost:{gold:500,wood:5,stone:5},unit:'militia'},
 castleRange:{id:'castleRange',faction:'castle',name:'Strzelnica',cost:{gold:1000,wood:10,stone:5},requires:['castleBarracks'],unit:'crossbowman'},
 castleSquireBastion:{id:'castleSquireBastion',faction:'castle',name:'Bastion Giermków',cost:{gold:1500,wood:5,stone:10,gems:2},requires:['castleBarracks'],unit:'squire'},
 castleGriffinTower:{id:'castleGriffinTower',faction:'castle',name:'Wieża Gryfa',cost:{gold:2500,stone:10,wood:5,gems:5},requires:['castleSquireBastion'],unit:'griffinGuard'},
 castleTownHall:{id:'castleTownHall',faction:'castle',name:'Ratusz',cost:{gold:1000,wood:5,stone:5},daily:{gold:500}}, castleMagistrate:{id:'castleMagistrate',faction:'castle',name:'Magistrat',cost:{gold:2500,wood:5,stone:10},requires:['castleTownHall'],daily:{gold:1000}}, castleTreasury:{id:'castleTreasury',faction:'castle',name:'Skarbiec Królewski',cost:{gold:5000,stone:10,gems:5},requires:['castleMagistrate'],daily:{gold:2000}},
 castleCommandHall:{id:'castleCommandHall',faction:'castle',name:'Sala Dowódcy',cost:{gold:1500,wood:5,stone:5},special:'morale'}, castleChapel:{id:'castleChapel',faction:'castle',name:'Kaplica',cost:{gold:1500,stone:5,gems:2},special:'lightMagic'}, castleWalls:{id:'castleWalls',faction:'castle',name:'Kamienne Mury',cost:{gold:2000,stone:15},special:'walls'},
 necroCrypt:{id:'necroCrypt',faction:'necropolis',name:'Krypta',cost:{gold:500,stone:5,soulMushrooms:2},unit:'skeleton'}, necroBoneTower:{id:'necroBoneTower',faction:'necropolis',name:'Kościana Wieża',cost:{gold:1000,wood:5,stone:5,soulMushrooms:3},requires:['necroCrypt'],unit:'boneArcher'}, necroTomb:{id:'necroTomb',faction:'necropolis',name:'Grobowiec Strażników',cost:{gold:1500,stone:10,mercury:2,soulMushrooms:4},requires:['necroCrypt'],unit:'tombGuard'}, necroPhantomStable:{id:'necroPhantomStable',faction:'necropolis',name:'Stajnia Widm',cost:{gold:2500,stone:10,mercury:5,soulMushrooms:6},requires:['necroTomb'],unit:'phantomRider'},
 necroTownHall:{id:'necroTownHall',faction:'necropolis',name:'Ratusz Umarłych',cost:{gold:1000,stone:5},daily:{gold:500}}, necroMagistrate:{id:'necroMagistrate',faction:'necropolis',name:'Magistrat Umarłych',cost:{gold:2500,stone:10},requires:['necroTownHall'],daily:{gold:1000}}, necroTreasury:{id:'necroTreasury',faction:'necropolis',name:'Skarbiec Krypt',cost:{gold:5000,stone:15,mercury:2},requires:['necroMagistrate'],daily:{gold:2000}},
 necroSoulAltar:{id:'necroSoulAltar',faction:'necropolis',name:'Ołtarz Dusz',cost:{gold:1500,stone:5,soulMushrooms:4},special:'necromancy'}, necroMycelium:{id:'necroMycelium',faction:'necropolis',name:'Grzybnia Umarłych',cost:{gold:2000,stone:5,soulMushrooms:5},daily:{soulMushrooms:1}}, necroMageTower:{id:'necroMageTower',faction:'necropolis',name:'Wieża Nekromanty',cost:{gold:2000,stone:5,mercury:3,soulMushrooms:3},special:'deathMagic'}
};
const FACTIONS={castle:{id:'castle',name:'Zamek',units:['militia','crossbowman','squire','griffinGuard','lightPriest','knight','paladin']},necropolis:{id:'necropolis',name:'Nekropolia',units:['skeleton','boneArcher','tombGuard','phantomRider','lich','vampireLord','necromancerArchmage']}};
function dayKey(c){return `${c.month}:${c.week}:${c.day}`;} function enough(res,cost={}){return Object.entries(cost).every(([k,v])=>(res[k]||0)>=v);} function pay(res,cost={}){for(const[k,v]of Object.entries(cost))res[k]-=v;}
function createTownState(faction,id){return{id,faction,owner:'player',buildings:[],availableRecruits:{},garrison:[],lastBuildDayKey:null};}
function canBuild(town,bid,res,cal){const b=BUILDINGS[bid];if(!b||b.faction!==town.faction)return{ok:false,reason:'wrong-faction'};if(town.buildings.includes(bid))return{ok:false,reason:'built'};if(town.lastBuildDayKey===dayKey(cal))return{ok:false,reason:'daily-limit'};if((b.requires||[]).some(x=>!town.buildings.includes(x)))return{ok:false,reason:'prerequisite'};if(!enough(res,b.cost))return{ok:false,reason:'resources'};return{ok:true};}
function build(town,bid,res,cal){const c=canBuild(town,bid,res,cal);if(!c.ok)return c;const b=BUILDINGS[bid];pay(res,b.cost);town.buildings.push(bid);town.lastBuildDayKey=dayKey(cal);if(b.unit&&town.availableRecruits[b.unit]==null)town.availableRecruits[b.unit]=0;return{ok:true,building:b};}
function applyWeeklyGrowth(town){for(const bid of town.buildings){const u=UNITS[BUILDINGS[bid]?.unit];if(u?.growth)town.availableRecruits[u.id]=(town.availableRecruits[u.id]||0)+u.growth;}return town.availableRecruits;}
function canRecruit(town,uid,count,res,army){const u=UNITS[uid],n=Math.max(0,Math.floor(count));if(!u||u.faction!==town.faction||n<1)return{ok:false,reason:'unit'};if((town.availableRecruits[uid]||0)<n)return{ok:false,reason:'available'};const cost=Object.fromEntries(Object.entries(u.cost||{}).map(([k,v])=>[k,v*n]));if(!enough(res,cost))return{ok:false,reason:'resources'};if(!army.some(s=>s.unitId===uid)&&army.length>=7)return{ok:false,reason:'slots'};return{ok:true,cost,u,n};}
function stackFromUnit(u,n){return{unitId:u.id,id:`stack-${u.id}`,name:u.name,type:u.type||'skeleton',variant:u.variant||'',count:n,hpPer:u.hpPer,totalHp:u.hpPer*n,minDmg:u.minDmg,maxDmg:u.maxDmg,speed:u.speed,attack:u.attack,defense:u.defense,size:u.size||1,mounted:!!u.mounted,ranged:!!u.ranged,shots:u.shots||0,maxShots:u.shots||0};}
function recruit(town,uid,count,res,army){const c=canRecruit(town,uid,count,res,army);if(!c.ok)return c;pay(res,c.cost);town.availableRecruits[uid]-=c.n;let s=army.find(x=>x.unitId===uid);if(s){s.count+=c.n;s.totalHp+=c.u.hpPer*c.n;}else army.push(stackFromUnit(c.u,c.n));return{ok:true,count:c.n};}
function transferStack(from,to,index){const s=from[index];if(!s)return{ok:false,reason:'empty'};const same=to.find(x=>x.unitId===s.unitId);if(!same&&to.length>=7)return{ok:false,reason:'slots'};from.splice(index,1);if(same){same.totalHp+=s.totalHp;same.count+=s.count;}else to.push(s);return{ok:true};}
function applyNecromancy(info,res,army){const rate=info.altar?.25:.20;const potential=Math.floor((info.defeatedModels||0)*rate);const maxByMush=(res.soulMushrooms||0)*10;let raised=Math.min(potential,maxByMush);if(raised<1)return{raised:0};let s=army.find(x=>x.unitId==='skeleton');if(!s&&army.length>=7)return{raised:0};const used=Math.ceil(raised/10);res.soulMushrooms-=used;if(s){s.count+=raised;s.totalHp+=raised*UNITS.skeleton.hpPer;}else army.push(stackFromUnit(UNITS.skeleton,raised));return{raised,mushroomsUsed:used};}
function dailyTownIncome(town,res){for(const bid of town.buildings){const daily=BUILDINGS[bid]?.daily||{};for(const[k,v]of Object.entries(daily))res[k]=(res[k]||0)+v;}return res;}
return{UNITS,BUILDINGS,FACTIONS,createTownState,canBuild,build,applyWeeklyGrowth,canRecruit,recruit,transferStack,applyNecromancy,dailyTownIncome,stackFromUnit};
});
