(()=>{let state=GameState.load();const params=new URLSearchParams(location.search),id=params.get('town')||'castle-haven';const definitions={'castle-haven':{name:'Forteca Świtu',faction:'castle'},'necropolis-morrow':{name:'Nekropolia Morrow',faction:'necropolis'}};const def=definitions[id]||definitions['castle-haven'];if(!state.towns[id])state.towns[id]=TownCore.createTownState(def.faction,id);const town=state.towns[id],$=x=>document.getElementById(x),status=$('townStatus');
const labels={stone:'🪨 Kamień',wood:'🪵 Drewno',mercury:'⚗️ Rtęć',sulfur:'🟡 Siarka',gems:'💎 Klejnoty',gold:'🪙 Złoto',soulMushrooms:'🍄 Grzyby Dusz'};function costText(cost={}){return Object.entries(cost).map(([k,v])=>`${labels[k]||k}: ${v}`).join(' · ')}
function save(){GameState.save(state)}function renderResources(){for(const k of GameState.RESOURCE_KEYS)$(`res-${k}`).textContent=state.resources[k]||0}
function renderBuildings(){const list=Object.values(TownCore.BUILDINGS).filter(b=>b.faction===town.faction);$('buildingsGrid').innerHTML=list.map(b=>{const built=town.buildings.includes(b.id),can=TownCore.canBuild(town,b.id,state.resources,state.calendar);return `<article class="building ${built?'built':''} ${!built&&!can.ok?'locked':''}"><h3>${built?'✅ ':'🏗️ '}${b.name}</h3><div class="cost">${built?'Zbudowano':costText(b.cost)}</div><small>${b.unit?`Siedlisko: ${TownCore.UNITS[b.unit].name}`:b.daily?`Dochód: ${costText(b.daily)} / dzień`:b.special?`Specjalne: ${b.special}`:''}</small>${built?'':`<button data-build="${b.id}" ${can.ok?'':'disabled'}>${can.ok?'Zbuduj':can.reason==='daily-limit'?'Limit budowy wykorzystany':'Niedostępne'}</button>`}</article>`}).join('');document.querySelectorAll('[data-build]').forEach(btn=>btn.onclick=()=>{const out=TownCore.build(town,btn.dataset.build,state.resources,state.calendar);status.textContent=out.ok?`Zbudowano: ${out.building.name}.`:`Nie można zbudować (${out.reason}).`;save();render()})}
function renderRecruit(){const dwellings=town.buildings.map(b=>TownCore.BUILDINGS[b]).filter(b=>b?.unit);$('recruitPanel').innerHTML=dwellings.length?dwellings.map(b=>{const u=TownCore.UNITS[b.unit],avail=town.availableRecruits[u.id]||0;return `<div class="recruit-row"><div><strong>${u.name}</strong><small>Poziom ${u.tier} · dostępne ${avail}<br>${costText(u.cost)} / szt.</small></div><div><input type="number" min="1" max="${avail}" value="${Math.max(1,Math.min(avail,1))}" id="qty-${u.id}"><button data-recruit="${u.id}" ${avail?'':'disabled'}>Rekrutuj</button></div></div>`}).join(''):'<p>Najpierw zbuduj siedlisko jednostek.</p>';document.querySelectorAll('[data-recruit]').forEach(btn=>btn.onclick=()=>{const uid=btn.dataset.recruit,n=+$(`qty-${uid}`).value;const out=TownCore.recruit(town,uid,n,state.resources,state.hero.army);status.textContent=out.ok?`Zrekrutowano ${out.count} × ${TownCore.UNITS[uid].name}.`:`Rekrutacja niemożliwa (${out.reason}).`;save();render()})}
function slots(arr,source){return Array.from({length:7},(_,i)=>{const s=arr[i];return `<div class="slot ${s?'':'empty'}" data-${source}="${i}">${s?`<b>${s.name}</b><span>${s.count}</span>`:'—'}</div>`}).join('')}
function renderArmies(){$('heroArmy').innerHTML=slots(state.hero.army,'hero');$('garrisonArmy').innerHTML=slots(town.garrison,'garrison');document.querySelectorAll('[data-hero]').forEach(e=>e.onclick=()=>{const i=+e.dataset.hero;if(state.hero.army[i]){const o=TownCore.transferStack(state.hero.army,town.garrison,i);status.textContent=o.ok?'Przeniesiono do garnizonu.':`Nie można przenieść (${o.reason}).`;save();render()}});document.querySelectorAll('[data-garrison]').forEach(e=>e.onclick=()=>{const i=+e.dataset.garrison;if(town.garrison[i]){const o=TownCore.transferStack(town.garrison,state.hero.army,i);status.textContent=o.ok?'Dołączono do armii bohatera.':`Nie można przenieść (${o.reason}).`;save();render()}})}
function render(){$('townName').textContent=def.name;$('townFaction').textContent=TownCore.FACTIONS[town.faction].name;$('townEmblem').textContent=town.faction==='castle'?'🏰':'☠️';$('townBackdrop').classList.toggle('necropolis',town.faction==='necropolis');$('townTagline').textContent=town.faction==='castle'?'Honor, kamień i stal':'Dusze pamiętają każde pole bitwy';renderResources();renderBuildings();renderRecruit();renderArmies()}
$('backToMapBtn').onclick=()=>{save();location.href='adventure.html'};render();save();})();
