const test=require('node:test');const assert=require('node:assert/strict');const T=require('../town-core.js');
const res=()=>({stone:99,wood:99,mercury:99,sulfur:99,gems:99,gold:99999,soulMushrooms:99});
test('faction trees include mounted 2-hex Paladin and Necromancer Archmage',()=>{assert.equal(T.UNITS.paladin.tier,7);assert.equal(T.UNITS.paladin.size,2);assert.equal(T.UNITS.paladin.mounted,true);assert.equal(T.UNITS.necromancerArchmage.tier,7);assert.equal(T.UNITS.necromancerArchmage.faction,'necropolis');});
test('only one building may be constructed per town per day',()=>{const town=T.createTownState('castle','c'),r=res();assert.equal(T.build(town,'castleBarracks',r,{day:1,week:1,month:1}).ok,true);assert.equal(T.build(town,'castleTownHall',r,{day:1,week:1,month:1}).ok,false);});
test('prerequisites and costs are enforced',()=>{const town=T.createTownState('castle','c'),poor={stone:0,wood:0,mercury:0,sulfur:0,gems:0,gold:0,soulMushrooms:0};assert.equal(T.canBuild(town,'castleRange',res(),{day:1,week:1,month:1}).ok,false);assert.equal(T.canBuild(town,'castleBarracks',poor,{day:1,week:1,month:1}).ok,false);});
test('weekly growth accumulates recruits for built dwellings',()=>{const town=T.createTownState('castle','c');town.buildings=['castleBarracks'];T.applyWeeklyGrowth(town);T.applyWeeklyGrowth(town);assert.equal(town.availableRecruits.militia,28);});
test('recruitment pays cost and adds stack',()=>{const town=T.createTownState('castle','c');town.buildings=['castleBarracks'];town.availableRecruits.militia=5;const r=res(),army=[];assert.equal(T.recruit(town,'militia',3,r,army).ok,true);assert.equal(army[0].count,3);assert.equal(r.gold,99999-165);});
test('whole-stack transfer merges same unit id',()=>{const a=[{unitId:'militia',count:2,hpPer:10,totalHp:20}],b=[{unitId:'militia',count:3,hpPer:10,totalHp:30}];assert.equal(T.transferStack(a,b,0).ok,true);assert.equal(b[0].count,5);});
test('necromancy is limited by Soul Mushrooms',()=>{const r=res();r.soulMushrooms=2;const army=[];const out=T.applyNecromancy({defeatedModels:200,altar:true},r,army);assert.equal(out.raised,20);assert.equal(r.soulMushrooms,0);});
